{% set name = "trove-classifiers" %}
{% set version = "2023.5.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trove-classifiers-{{ version }}.tar.gz
  sha256: fd5a1546283be941f47540a135bdeae8fb261380a6a204d9c18012f2a1b0ceae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - calver
    - pip
  run:
    - python >=3.6

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
